name: katex
version: 0.1.0
author: Adam J. Cook <adam.joseph.cook@gmail.com>
description: Fast math typesetting for the web, ported to Dart.
homepage: https://github.com/adamjcook/katex.dart
dependencies:
  logging: '>=0.9.2 <0.10.0'
  quiver: '>=0.18.2 <0.19.0'
dev_dependencies:
  core_elements: '>=0.2.1+1 <0.3.0'
  html5lib: '>=0.12.0 <0.13.0'
  paper_elements: '>=0.2.0 <0.3.0'
  path: '>=1.3.0 <2.0.0'
  polymer: '>=0.14.0+1 <0.15.0'
  unittest: '>=0.11.0+5 <0.12.0'
  web_components: '>=0.7.0 <0.8.0'
  yaml: '>=2.0.1+1 <3.0.0'
environment:
  sdk: '>=1.6.0'
transformers:
- polymer:
    entry_points:
    - web/index.html
    lint: false